import math
r=float(input('input the radius of the circle:'))
a=math.pi*r*r
print('the area of the circlewith radius', r, 'is:',a)


fn=input('Input the Filename: ')
f=fn.split(".")
d={
    'AAPKG':'ArchestrA IDE',
    'AAC':'Advanced Audio Coding',
    'ace':'ACE compressed file',
    'ALZ':'ALZip compressed file',
    'APK':'Android package',
    'APPX':'Microsoft Application Package (.appx)',
    'AT3':'Sony UMD data compression',
    'bke':'BackupEarth.com data compression',
    'ARC':'pre-Zip data compression',
    'ARC':'Nintendo U8 Archive',
    'ARJ':'ARJ compressed file',
    'ASS':'a video typesetting application also a Halo game engine file',
    'B':'(B file) Similar to .a, but less compressed',
    'ba':'Scifer Archive (.ba), Scifer External Archive Type',
    'big':'Special file compression format used by Electronic Arts to compress the data for many of EA games',
    'BIN':'compressed archive, can be read and used by CD-ROMs and Java, extractable by 7-zip and WINRAR',
    'bjsn':'Used to store The Escapists saves on Android',
    'bkf':'Microsoft backup created by NTBackup.c',
    'bld':'Skyscraper Simulator Building',
    'cab':'A cabinet (.cab) file is a library of compressed files stored as one file.',
    'c4':'JEDMICS image files, a DOD system',
    'cals':'JEDMICS image files, a DOD system',
    'xaml':'Used in programs like Visual Studio to create exe files.',
    'CLIPFLAIR':'ClipFlair Studio ClipFlair component saved state file',
    'CPT':'Compact Pro (Macintosh)',
    'DAA':'Closed-format, Windows-only compressed disk image',
    'deb':'Debian install package',
    'DMG':'an Apple compressed/encrypted format',
    'DDZ':'a file which can only be used by the "daydreamer engine" created by "fever-dreamer"',
    'DN':'Adobe Dimension CC file format',
    'DPE':'Package of AVE documents made with Aquafadas digital publishing tools.',
    'egg':'Alzip Egg Edition compressed file',
    'egt':'EGT Universal Document also used to create compressed cabinet files replaces .ecab',
    'ECAB':'EGT Compressed Folder used in advanced systems to compress entire system folders, replaced by EGT Universal Document',
    'ESD':'Electronic Software Distribution, a compressed and encrypted WIM File',
    'ess':'EGT SmartSense File, detects files compressed using the EGT compression system.',
    'exe':'Windows application',
    'flipchart':'Used in Promethean ActivInspire Flipchart Software',
    'GBP':'GBP File Extension to the files that the user has chosen to backup',
    'gerbv':'A Free/Open Source Gerber Viewer on Mac using Autodesk EAGLE, Gerbv, gEDA gplEDA Homepage and on Linux using Autodesk EAGLE, gEDA, Gerbv',
    'gbs':'OtterUI binary scene file',
    'gho':'Norton Ghost',
    'gif':'Graphics Interchange Format',
    'gz':'Compressed file',
    'html':'HTML code file',
    'IPG':'Format in which Apple Inc. packages their iPod games. can be extracted through Winrar',
    'jar':'ZIP file with manifest for use with Java applications.',
    'LBR':'Lawrence Compiler Type file',
    'LBR':'Library file',
    'LQR':'LBR Library file compressed by the SQ program.',
    'lzh':'Lempel, Ziv, Huffman',
    'lz':'Compressed file',
    'lzma':'Lempel–Ziv–Markov chain algorithm compressed file',
    'mbw':'MBRWizard archive',
    'MHTML':'Mime HTML (Hyper-Text Markup Language) code file',
    'mpq':'Used by Blizzard Entertainment',
    'bin':'MacBinary',
    'NL2PKG':'NoLimits 2 Package (.nl2pkg)',
    'nth':'Nokia Theme Used by Nokia Series 40 Cellphones',
    'oar':'OAR archive',
    'OSK':'Compressed osu! skin archive',
    'OSR':'Compressed osu! replay archive',
    'OSZ':'Compressed osu! beatmap archive',
    'PAK':'Enhanced type of .ARC archive',
    'par':'Parchive',
    'paf':'Portable Application File',
    'pea':'PeaZip archive file',
    'php':'PHP code file',
    'pyk':'Compressed file',
    'pk3':'Quake 3 archive (See note on Doom³)',
    'pk4':'Doom³ archive (Opens similarly to a zip archive.)',
    'py':'Python code file',
    'rar':'Rar Archive, for multiple file archive (rar to .r01-.r99 to s01 and so on)',
    'RAG':'Game file',
    'RaX':'Archive file created by RaX',
    'RBXL':'Roblox Studio place file',
    'RBXLX':'Roblox Studio XML place file',
    'RBXM':'Roblox studio script file',
    'RPM':'Red Hat package/installer for Fedora, RHEL, and similar systems.',
    'sb':'Scratch file',
    'sb2':'Scratch 2.0 file',
    'sb3':'Scratch 3.0 file',
    'SEN':'Scifer Archive (.sen) – Scifer Internal Archive Type',
    'SIT':'StuffIt (Macintosh)',
    'SIS':'Symbian Application Package',
    'SKB':'Google SketchUp backup File',
    'SQ':'Squish Compressed Archive',
    'SWM':'Splitted WIM File',
    'SZS':'Nintendo Yaz0 Compressed Archive',
    'TAR':'group of files, packaged as one file',
    'TGZ':'gzipped tar file',
    'TB':'Tabbery Virtual Desktop Tab file',
    'TIB':'Acronis True Image backup',
    'UHA':'Ultra High Archive Compression',
    'UUE':'unified utility engine – the generic and default format for all things UUe-related.',
    'VIV':'Archive format used to compress data for several video games, including Need For Speed: High Stakes.',
    'VOL':'video game data package.',
    'VSA':'Altiris Virtual Software Archive',
    'WAX':'Wavexpress',
    'WIM':'A compressed disk image for installing Windows Vista or higher, Windows Fundamentals for Legacy PC, or restoring a system image made from Backup and Restore (Windows Vista/7)',
    'XAP':'Windows Phone Application Package',
    'xz':'xz compressed files, based on LZMA/LZMA2 algorithm',
    'Z':'Unix compress file',
    'zoo':'based on LZW',
    'zip':'popular compression format',
    }
a=f[1]
print (d.get(a))
